matrix:
- name: Markdown
  apsell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    - wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  sources:
  - '**/*.md'
  expect_match: true
