matrix:
- name: Markdown
  apsell:
    mode: none
  dictionary:
    wordlists:
    - wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
  - pyspelling.filters.text:
  sources:
  - '**/*.md'
  expect_match: true
