matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    - ./wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences:
  sources:
  - '**/*.md'
  expect_match: true
