---


matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: true
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8
