---

name: 'Add issue to project board'

"on":
  issues:
    types:
      - opened
env:
  GH_TOKEN: ${{ secrets.GH_NEW_CARD_TO_PROJECT }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  ISSUE_ID: ${{ github.event.issue.node_id }}
  USER: ${{ github.actor }}

jobs:
  add_issue:
    runs-on: ubuntu-latest
    steps:
      - name: "Add issue"
        run: |
          gh api graphql -f query='
            mutation($user:String!, $project:ID!, $issue:ID!) {
              addProjectV2ItemById(input: {clientMutationId: $user, projectId: $project, contentId: $issue}) {
                item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID -f user=$USER

      - name: "Add repo identifier label"
        run: |
          gh api graphql -f query='
            mutation($user:String!, $issue:ID!, $labels:[ID!]!) {
              addLabelsToLabelable(input: {clientMutationId: $user, labelableId: $issue, labelIds: $labels}) {
                clientMutationId
              }
            }
            {
              labels: "LA_kwDOHYOSis73zvVw", "LA_kwDOHYOSis73znqb"
            }' -f issue=$ISSUE_ID -f user=$USER
