---


name: 'Conventional commits'

"on":
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  #######
  ## Conventional Commits
  #######

  # Uses https://github.com/aevea/commitsar
  conventional-commits:
    name: Verify conventional commits
    if: |
      contains(github.event.*.name, 'edited') == true ||
      contains(github.event.*.name, 'synchronize') == true ||
      contains(github.event.*.name, 'opened') == true ||
      contains(github.event.*.name, 'reopened') == true ||
      contains(github.event.*.name, 'ready_for_review') == true ||
      contains(github.event.*.name, 'converted_to_draft') == true ||
      contains(github.event.*.name, 'ready_for_review') == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Commitsar conventional commits check
        if: steps.check-out.outcome == 'success'
        uses: aevea/commitsar@v0.18.0
