---


name: 'Spellcheck action'

"on":
  push:
    branches:
      - '**'
jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Use custom config file
      uses: crate-ci/typos@v1.8.1
      with: 
        files: '**/**.md'
        config: .typos.toml
