---


name: 'Spellcheck action'

"on":
  push:
    branches:
      - '**'
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.24.0
      name: Spellcheck
      with:
        config_path: .github/workflows/actions/.spellcheck.yml # put path to configuration file here
        source_files: README.md
        task_name: Markdown
