---


name: 'Spellcheck action'

"on":
  push:
    branches:
      - '**'
jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Run PySpelling
      uses: rojopolis/spellcheck-github-actions@0.24.0
      with:
        task_name: Markdown
        output_file: spellcheck-output.txt
