---


name: 'Spellcheck action'

"on":
  push:
    branches:
      - '**'
jobs:
  spellcheck:
    name: runner / spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Run PySpelling
      uses: sbates130272/spellcheck-github-actions@v0.7.0
